logging:
  level:
    root: INFO
  pattern:
    level: '''%clr(%5p) %clr([%X{traceId:-} %X{spanId:-} %X{transaction-id:-}]){green}'''
spring:
  sleuth:
    baggage:
      correlation-fields: transaction-id
      remote-fields: transaction-id
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
