logging:
  level:
    root: INFO
  pattern:
    level: '''%clr(%5p) %clr([%X{traceId:-} %X{spanId:-} %X{transaction-id:-}]){green}'''
spring:
  sampler:
    probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost