eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
spring:
  application:
    name: MONGODEMO
  data:
    mongodb:
      uri: mongodb+srv://test:test123@cluster0.fmeh0x9.mongodb.net/empdb
